runnerImage:
  image: dreamsports.jfrog.io/d11-docker-artifacts/actions-runner-maven:ubuntu-20.04

labels:
  - self-hosted
  - linux
  - X64
  - k8s
  - codepush-web-dashboard

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 20

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: 'arn:aws:iam::954754807219:role/ci-cluster-service-account-role'