name: Onboard Ephemeral Runners

run-name: ${{ github.repository }} repository ephemeral runners

on: workflow_dispatch

jobs:
  onboarding-job:
    runs-on: onboarding-runner
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Onboard Ephemeral Runners Action
        id: onboarding
        uses: dream11/k8s-action-runner@v2.0.1
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          values-file: '.ci/actions/values.yml'
          docker-username: ${{ secrets.JFROG_USERNAME }}
          docker-password: ${{ secrets.JFROG_PASSWORD }}
          helm-username: ${{ secrets.JFROG_USERNAME }}
          helm-password: ${{ secrets.JFROG_PASSWORD }}