/**
 * Release Creation Types
 * 
 * @deprecated This file contains legacy types that are being replaced.
 * 
 * MIGRATION GUIDE:
 * - Use `~/types/release-creation-backend` for new backend-compatible types
 * - `ReleaseBasicDetails` → Use `ReleaseCreationState` from release-creation-backend.ts
 * - `ReleaseCustomizations` → Use `CronConfig` from release-creation-backend.ts
 * 
 * These types will be removed after all components are migrated.
 * See RELEASE_CREATION_REFACTOR_PLAN.md for migration details.
 */

import type { ReleaseConfiguration, RegressionSlot } from './release-config';

/**
 * @deprecated Use ReleaseCreationState from release-creation-backend.ts
 * This type uses old format incompatible with backend API
 */
export interface ReleaseCreationMode {
  type: 'WITH_CONFIG' | 'MANUAL';
  configId?: string; // If WITH_CONFIG
}

/**
 * @deprecated Use ReleaseCreationState from release-creation-backend.ts
 * Old format: Uses boolean object for targets, separate version field
 * New format: Uses platformTargets array with per-platform versions
 */
export interface ReleaseBasicDetails {
  version: string; // Autogenerated but editable
  releaseType: 'MAJOR' | 'MINOR' | 'HOTFIX'; // Prefilled from config, disabled (deprecated - use ReleaseCreationState)
  baseBranch: string; // Prefilled from config, but editable
  
  // Release DateTime
  releaseDate: string; // ISO date string
  releaseTime?: string; // HH:MM format, optional (default: no)
  
  // Branch Fork off DateTime (Kickoff)
  kickoffDate: string; // ISO date string, default: RD-2days
  kickoffTime?: string; // HH:MM format
  
  // Regression Build DateTime
  hasRegressionBuilds: boolean; // Yes/No toggle
  regressionBuildSlots?: RegressionSlot[]; // List of slots if hasRegressionBuilds = true
  
  // Release Targets (from config options)
  // @deprecated Use platformTargets array instead
  releaseTargets: {
    web: boolean;
    playStore: boolean;
    appStore: boolean;
  };
  
  description?: string;
}

/**
 * @deprecated Use CronConfig from release-creation-backend.ts
 * Old format: Only 2 boolean toggles
 * New format: Full cronConfig object with all options
 */
export interface ReleaseCustomizations {
  // Only 2 boolean toggles
  enablePreRegressionBuilds: boolean; // Only shown if config has pre-regression builds
  enableCheckmate: boolean; // Only shown if config has checkmate configured
}

export interface CompleteReleaseData {
  tenantId: string;
  configId?: string; // Reference to configuration used (null for manual mode)
  
  basicDetails: ReleaseBasicDetails;
  customizations: ReleaseCustomizations;
  
  // Merged data (for backend)
  mergedConfig?: Partial<ReleaseConfiguration>;
}

// Validation rules (for documentation/reference)
export const ReleaseValidationRules = {
  version: {
    required: true,
    pattern: /^v?\d+\.\d+\.\d+$/, // Semantic versioning (with optional 'v' prefix)
  },
  releaseDate: {
    required: true,
    mustBeFuture: true,
  },
  kickoffDate: {
    required: true,
    mustBeBeforeRelease: true,
    defaultOffsetDays: 2, // RD-2days
  },
  regressionBuildSlots: {
    validateTime: true,
    mustBeBetweenKickoffAndRelease: true,
  },
  releaseTargets: {
    minSelected: 1, // At least one platform
  },
} as const;

export interface ReleaseCreationStep {
  id: string;
  title: string;
  description: string;
  isComplete: boolean;
}

